Repository replit/polygott, pull requests merged in 2021-01, with the labels that each got.

#194 Merge the goval polygott with the polygott polygott
  Dockerfile
  Makefile
  README.md
  extra/_test_runner.py
  extra/apt-install
  extra/config.toml
  extra/cquery11
  extra/matplotlibrc
  extra/pycodestyle
  extra/pylintrc
  extra/replit-v2.py
  fluxbox-init
  gen/inside-test.ejs
  gen/lang-setup.ejs
  gen/phase0.ejs
  gen/x11-vnc.ejs
  lang-gitignore
  languages/assembly.toml
  languages/pyxel.toml
  languages/swift.toml
  packages.txt
  run_dir/findreqs.py
  run_dir/hamcrest-core-1.3.jar
  run_dir/json-simple-1.1.1.jar
  run_dir/junit-4.12.jar
  run_dir/parser.py
  run_dir/remotedebugger.py
  run_dir/repl.py
  run_dir/replit.py
  run_dir/sitecustomize.py
  run_dir/subprocessdebugger.py
  xorg.conf
Labels: hefty

#196 Build an image with just the languages needed for CI
  .circleci/config.yml
  Makefile
Labels: boop, bop

#197 Add java10 to the polygott-ci image
  Makefile
Labels: bop

#199 Upgrade python-language-server and related packages
  languages/python3.toml
Labels: bop

#203 Make new fluxbox windows always start at (0,0)
  Dockerfile
  extra/fluxbox/apps
  extra/fluxbox/init
Labels: bop

#204 Fix the detect-language script
  gen/detect-language.ejs
Labels: bop
